### ISSUE TITLE
Support for other mob types like Pillager and Vindicator

### ISSUE THREAD

**Issue by Mqxx** [Explorers-Eden/Nice-Villager-Leashing#1]
Hey, I like the Datapack. Could you add support for other entity types like Piller and Vindicators. You could implement an entity tag list to configure the mobs. Maybe I have the time to create a PR for adding this feature. 😃

**Comment by NiceKaleido** [comment]
Feel free to pull and make your own version. But keep in mind that other entities cannot be triggered via interaction advancement, so you'd have to figure out a different way.
